/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.yury.smirnov.aoc2020;

import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static com.github.yury.smirnov.aoc2020.Day1ReportRepair.SUM_2020;
import static org.junit.Assert.assertEquals;

public class Day1ReportRepairTest {

    private Day1ReportRepair day1ReportRepair = new Day1ReportRepair();
    private int[] inputValues;

    @Before
    public void setUp() throws IOException {
        Path sourcePath = Paths.get("src/test/resources/day1_input.txt");
        inputValues = Files.readAllLines(sourcePath).stream()
                .mapToInt(Integer::parseInt)
                .toArray();
    }

    @Test
    public void test_sum2020_findTwoNumbers_returnsExpectedProduct() {
        assertEquals(787776, day1ReportRepair.findProductOfTwoForSum(SUM_2020, inputValues));
    }

    @Test
    public void test_sum_2020_findThreeNumbers_returnsExpectedProduct() {
        assertEquals(262738554, day1ReportRepair.findProductOfThreeForSum(SUM_2020, inputValues));
    }
}
